-- Create Database --

CREATE TABLE Responsible(
   ID_R INT PRIMARY KEY NOT NULL IDENTITY,
   N_R VARCHAR(30),
   S_R VARCHAR(30),
   HD_R DATE,
);

CREATE TABLE Customers(
   ID_C INT PRIMARY KEY NOT NULL IDENTITY,
   N_C VARCHAR(30),
   S_C VARCHAR(30),
   BD_C DATE,
);

CREATE TABLE Customer_Order(
   ID_O INT PRIMARY KEY NOT NULL IDENTITY,
   R_O VARCHAR(60),
   DD_O DATE,
   SD_O DATE,
   PD_O DATE,
   MOP_O VARCHAR(30),
   HT_O float,
   TVA_O DECIMAL(3,2),
   TTC_O float,
   ID_C INT NOT NULL,
   FOREIGN KEY(ID_C) REFERENCES Customers(ID_C)
);

CREATE TABLE Article(
   ID_A INT PRIMARY KEY NOT NULL IDENTITY,
   R_A VARCHAR(60),
   N_A VARCHAR(50),
   QC_A INT,
   QS_A INT,
   RT_A INT,
   HT_A float,
   TVA_A DECIMAL(3,2),
   D_A VARCHAR(100),

);

CREATE TABLE Adresse(
   ID_A INT PRIMARY KEY NOT NULL IDENTITY,
   ID_C INT NOT NULL,
   FOREIGN KEY(ID_C) REFERENCES Customers(ID_C)
);

CREATE TABLE City(
   ID_CY INT PRIMARY KEY NOT NULL IDENTITY,
   N_V VARCHAR(50),
);

CREATE TABLE Street_Name(
   ID_SN INT PRIMARY KEY NOT NULL IDENTITY,
   SN VARCHAR(100),
);

CREATE TABLE Street_Number(
   ID_SNB INT PRIMARY KEY NOT NULL IDENTITY,
   SNB INT,
);

CREATE TABLE Post_Code(
   ID_PC INT PRIMARY KEY NOT NULL IDENTITY,
   PC INT,
);

CREATE TABLE Employee(
   ID_E INT PRIMARY KEY NOT NULL IDENTITY,
   N_E VARCHAR(30),
   S_E VARCHAR(30),
   HD_E DATE,
   ID_A INT NOT NULL,
   ID_R INT NOT NULL,
   FOREIGN KEY(ID_A) REFERENCES Adresse(ID_A),
   FOREIGN KEY(ID_R) REFERENCES Responsible(ID_R)
);

CREATE TABLE composed(
   ID_O INT,
   ID_A INT,
   PRIMARY KEY(ID_O, ID_A),
   FOREIGN KEY(ID_O) REFERENCES Customer_Order(ID_O),
   FOREIGN KEY(ID_A) REFERENCES Article(ID_A)
);

CREATE TABLE Asso_4(
   ID_A INT,
   ID_SNB INT,
   PRIMARY KEY(ID_A, ID_SNB),
   FOREIGN KEY(ID_A) REFERENCES Adresse(ID_A),
   FOREIGN KEY(ID_SNB) REFERENCES Street_Number(ID_SNB)
);

CREATE TABLE Asso_5(
   ID_SN INT,
   ID_SNB INT,
   PRIMARY KEY(ID_SN, ID_SNB),
   FOREIGN KEY(ID_SN) REFERENCES Street_Name(ID_SN),
   FOREIGN KEY(ID_SNB) REFERENCES Street_Number(ID_SNB)
);

CREATE TABLE Asso_3(
   ID_A INT,
   ID_SN INT,
   PRIMARY KEY(ID_A, ID_SN),
   FOREIGN KEY(ID_A) REFERENCES Adresse(ID_A),
   FOREIGN KEY(ID_SN) REFERENCES Street_Name(ID_SN)
);

CREATE TABLE Asso_2(
   ID_CY INT,
   ID_SN INT,
   PRIMARY KEY(ID_CY, ID_SN),
   FOREIGN KEY(ID_CY) REFERENCES City(ID_CY),
   FOREIGN KEY(ID_SN) REFERENCES Street_Name(ID_SN)
);

CREATE TABLE Asso_1(
   ID_CY INT,
   ID_PC INT,
   PRIMARY KEY(ID_CY, ID_PC),
   FOREIGN KEY(ID_CY) REFERENCES City(ID_CY),
   FOREIGN KEY(ID_PC) REFERENCES Post_Code(ID_PC)
);

CREATE TABLE Asso(
   ID_A INT,
   ID_CY INT,
   PRIMARY KEY(ID_A, ID_CY),
   FOREIGN KEY(ID_A) REFERENCES Adresse(ID_A),
   FOREIGN KEY(ID_CY) REFERENCES City(ID_CY)
);
